const N=100,S=15;
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const repeat100=a=>{const out=[];for(let i=0;out.length<N;i++)out.push({...a[i%a.length],_seed:i});return shuffle(out)};
const opts=(correct,others)=>shuffle([correct,...others.filter(x=>x!==correct)] .slice(0,4));
const fb=(why,example)=>({why,example});

const terms=[
['testa','голова','Mi fa male la testa.','La parte superiore del corpo, sopra il collo.'],['viso','обличчя','Lava il viso ogni mattina.','La parte anteriore della testa.'],['occhio','око','Ho un po’ di polvere nell’occhio.','Organo della vista.'],['orecchio','вухо','Mi fa male l’orecchio destro.','Organo dell’udito.'],['naso','ніс','Ho il naso chiuso.','Organo che serve soprattutto per respirare e sentire gli odori.'],['bocca','рот','Apri la bocca, per favore.','Apertura attraverso cui mangiamo e parliamo.'],['dente','зуб','Mi lavo i denti dopo colazione.','Parte dura della bocca usata per mordere e masticare.'],['lingua','язик','La lingua mi brucia perché la zuppa è calda.','Organo nella bocca usato per gustare e parlare.'],['labbro','губа','Ho un piccolo taglio sul labbro.','Parte morbida che forma il bordo della bocca.'],['collo','шия','Mi fa male il collo dopo aver dormito male.','Parte del corpo tra testa e tronco.'],['spalla','плече','Porto la borsa sulla spalla.','Parte del corpo che collega il braccio al tronco.'],['braccio','рука','Alzo il braccio per fare una domanda.','Parte dell’arto superiore tra spalla e gomito.'],['gomito','лікоть','Mi sono appoggiato sul gomito.','Articolazione tra braccio e avambraccio.'],['mano','кисть / рука','Lavo le mani prima di mangiare.','Parte finale del braccio, con dita e palmo.'],['dito','палець','Mi sono tagliato un dito.','Una delle cinque parti mobili della mano.'],['petto','груди','Sento il respiro nel petto.','Parte anteriore del tronco.'],['schiena','спина','Ho mal di schiena.','Parte posteriore del tronco.'],['pancia','живіт','Dopo pranzo ho la pancia piena.','Parte anteriore del corpo tra petto e bacino.'],['gamba','нога','Mi fa male una gamba.','Parte dell’arto inferiore.'],['ginocchio','коліно','Mi sono fatto male al ginocchio.','Articolazione tra coscia e gamba.'],['caviglia','щиколотка','Ho preso una storta alla caviglia.','Articolazione tra gamba e piede.'],['piede','стопа','Ho i piedi freddi.','Parte finale della gamba usata per camminare.'],['tallone','п’ята','Mi fa male il tallone quando cammino.','Parte posteriore del piede.'],['dito del piede','палець ноги','Ho urtato un dito del piede contro il tavolo.','Una delle dita che si trovano sul piede.'],['pelle','шкіра','La pelle è molto secca in inverno.','Tessuto che riveste e protegge il corpo.'],['capello','волосся / волосина','Ho trovato un capello sulla giacca.','Uno dei peli che crescono sulla testa.'],['cuore','серце','Il cuore batte più velocemente dopo la corsa.','Organo che pompa il sangue nel corpo.'],['polmone','легеня','I polmoni servono per respirare.','Organo coinvolto nella respirazione.'],['stomaco','шлунок','Ho lo stomaco pesante dopo aver mangiato troppo.','Organo in cui arriva il cibo dopo averlo ingerito.'],['cervello','мозок','Il cervello controlla molte funzioni del corpo.','Organo principale del sistema nervoso.']
];

const guessBase=terms.map(([w,u,e,d],i)=>({prompt:d,correct:w,options:opts(w,terms.map(x=>x[0]).filter(x=>x!==w).slice(i%12,i%12+8)),feedback:fb(`La parola corretta è “${w}”.`,e)}));
function buildGuess(){return repeat100(guessBase)}

const intrusoBase=[
[['occhio','orecchio','naso','ginocchio'],'ginocchio','Gli altri tre si trovano nella testa o nel viso.'],
[['mano','dito','gomito','stomaco'],'stomaco','Gli altri tre appartengono all’arto superiore.'],
[['gamba','ginocchio','caviglia','lingua'],'lingua','Gli altri tre appartengono all’arto inferiore.'],
[['bocca','dente','lingua','spalla'],'spalla','Gli altri tre sono parti della bocca.'],
[['petto','schiena','pancia','orecchio'],'orecchio','Gli altri tre sono parti del tronco.'],
[['cuore','polmone','cervello','dito'],'dito','Gli altri tre sono organi interni.'],
[['capello','pelle','unghia','stomaco'],'stomaco','Gli altri tre sono elementi esterni del corpo.'],
[['braccio','avambraccio','gomito','piede'],'piede','Gli altri tre appartengono all’arto superiore.'],
[['tallone','piede','dito del piede','collo'],'collo','Gli altri tre sono parti del piede.'],
[['viso','testa','collo','ginocchio'],'ginocchio','Gli altri tre sono parti della zona superiore del corpo.'],
[['spalla','braccio','gomito','caviglia'],'caviglia','Gli altri tre appartengono al braccio e alla spalla.'],
[['stomaco','cuore','polmone','mano'],'mano','Gli altri tre sono organi interni.']
];
function buildIntruso(){return repeat100(intrusoBase.map(x=>({kind:'intruso',prompt:'Quale parola non appartiene al gruppo?',choices:x[0],correct:x[1],feedback:fb(`“${x[1]}” è l’intruso. ${x[2]}`,`Per esempio: possiamo parlare di ${x[0].filter(w=>w!==x[1])[0]} quando descriviamo il corpo.`)})))}

const completeBase=[
['Mi lavo i ___ dopo ogni pasto.','denti',['piedi','capelli','gomiti']],['Ho un po’ di polvere nell’___.','occhio',['orecchio','naso','stomaco']],['Porto lo zaino sulla ___.','spalla',['schiena','caviglia','pancia']],['Mi fa male il ___. Ho dormito in una posizione scomoda.','collo',['ginocchio','dito','piede']],['Dopo la corsa il mio ___ batte forte.','cuore',['stomaco','gomito','tallone']],['Mi sono fatto male al ___. Non riesco a piegarlo bene.','ginocchio',['capello','labbro','orecchio']],['Ho le mani fredde, soprattutto le ___ sono gelate.','dita',['spalle','gambe','labbra']],['La scarpa mi fa male sul ___.','tallone',['gomito','collo','petto']],['Mastico il cibo con i ___.','denti',['polmoni','capelli','piedi']],['Il medico ascolta il mio ___.','petto',['dito','viso','capello']],['Mi pettino i ___.','capelli',['piedi','gomiti','denti']],['Ho mal di ___. Dopo aver mangiato troppo mi sento pesante.','stomaco',['spalla','orecchio','ginocchio']],['Con il ___ sentiamo i suoni.','orecchio',['naso','cuore','gomito']],['Con il ___ sentiamo gli odori.','naso',['piede','petto','ginocchio']],['Uso le ___ per camminare.','gambe',['mani','orecchie','labbra']],['Il ___ protegge gli organi nella testa.','cranio',['gomito','tallone','polso']],['Con la ___ tocchiamo e afferriamo gli oggetti.','mano',['lingua','pancia','caviglia']],['La ___ ricopre tutto il corpo.','pelle',['lingua','schiena','gola']],['Dopo aver mangiato, sento lo ___ pieno.','stomaco',['orecchio','gomito','dito']],['Quando sorrido, si vedono i miei ___.','denti',['polmoni','capelli','ginocchia']]
];
function buildComplete(){return repeat100(completeBase.map(x=>({kind:'mc',prompt:x[0],correct:x[1],options:opts(x[1],x[2]),feedback:fb(`“${x[1]}” completa correttamente la frase.`,`Per esempio: ${x[1].charAt(0).toUpperCase()+x[1].slice(1)} è una parola comune quando descriviamo il corpo.`)})))}

const roleplayBase=[
['Sei dal medico. Vuoi spiegare che ti fa male la schiena.','Cosa dici?','Mi fa male la schiena.','È una frase semplice e naturale per indicare dove senti dolore.','Per esempio: Mi fa male il ginocchio.'],
['Un insegnante ti chiede perché tieni la mano alzata. Vuoi dire che hai dolore al braccio.','Cosa dici?','Mi fa male il braccio.','Indichi chiaramente la parte del corpo che ti fa male.','Per esempio: Ho male alla spalla.'],
['Sei in farmacia e vuoi comprare qualcosa perché hai le labbra secche.','Cosa dici?','Avete qualcosa per le labbra secche?','Descrivi il problema e chiedi un prodotto adatto.','Per esempio: Avete una crema per le mani?'],
['Un amico ti chiede perché cammini lentamente. Hai male alla caviglia.','Cosa rispondi?','Ho male alla caviglia.','La risposta spiega direttamente il motivo del movimento.','Per esempio: Ho preso una storta e mi fa male il piede.'],
['Durante una visita ti chiedono dove senti fastidio dopo aver mangiato.','Cosa dici?','Sento un fastidio allo stomaco.','Indichi la zona e il tipo di sensazione.','Per esempio: Sento un dolore al fianco.'],
['Devi spiegare che hai difficoltà a sentire i suoni.','Cosa dici?','Faccio fatica a sentire dall’orecchio destro.','La frase specifica il problema e il lato del corpo.','Per esempio: Vedo poco da un occhio.'],
['Ti chiedono di indicare la parte del corpo tra il braccio e la mano.','Cosa rispondi?','Il polso.','È il nome della parte richiesta.','Per esempio: Il gomito è tra il braccio e l’avambraccio.'],
['Vuoi dire che dopo una corsa respiri velocemente.','Cosa dici?','Dopo la corsa respiro molto velocemente.','Descrivi una situazione concreta usando il verbo respirare.','Per esempio: Dopo le scale respiro più forte.'],
['Hai freddo alle mani e vuoi dirlo a un amico.','Cosa dici?','Ho le mani fredde.','È una formulazione naturale e diretta.','Per esempio: Ho i piedi freddi.'],
['Un medico ti chiede se riesci a muovere il ginocchio.','Come rispondi?','Sì, ma mi fa male quando lo piego.','La risposta indica sia la possibilità di muoversi sia il dolore.','Per esempio: Riesco a camminare, ma lentamente.'],
['Vuoi spiegare che hai sbattuto il gomito contro una porta.','Cosa dici?','Ho sbattuto il gomito contro la porta.','Descrive chiaramente cosa è successo e quale parte del corpo è coinvolta.','Per esempio: Ho sbattuto il piede contro il tavolo.'],
['Ti chiedono cosa usi per vedere.','Cosa rispondi?','Gli occhi.','Gli occhi sono gli organi della vista.','Per esempio: Uso le orecchie per sentire.']
];
function buildRoleplay(){return repeat100(roleplayBase.map(x=>({kind:'mc',prompt:`${x[0]} ${x[1]}`,correct:x[2],options:opts(x[2],roleplayBase.map(y=>y[2])),feedback:fb(x[3],x[4])})))}

const situationsBase=[
['Hai mal di schiena dopo aver passato molte ore seduto.','Cosa puoi fare?','Cambiare posizione, fare una pausa e muoverti un po’.','Per esempio: Dopo molto tempo al computer, alzati e fai qualche passo.'],
['Hai un piccolo taglio sul dito mentre cucini.','Cosa fai?','Ti fermi e proteggi la zona con una medicazione adatta.','Per esempio: Lava con cura una piccola ferita e proteggila secondo le indicazioni ricevute.'],
['Hai gli occhi stanchi dopo molte ore davanti allo schermo.','Cosa puoi fare?','Fare una pausa e riposare gli occhi.','Per esempio: Allontanati dallo schermo per qualche minuto.'],
['Hai preso una storta alla caviglia e fai fatica a camminare.','Cosa fai?','Eviti di forzare la caviglia e chiedi consiglio se il dolore è importante.','Per esempio: Se il dolore è forte o persiste, chiedi una valutazione professionale.'],
['Hai mangiato molto velocemente e senti lo stomaco pesante.','Cosa puoi fare?','Riposarti e aspettare che la sensazione passi.','Per esempio: Una passeggiata tranquilla può essere più adatta di un’attività intensa.'],
['Ti accorgi di avere le mani molto fredde.','Cosa puoi fare?','Scaldarle gradualmente.','Per esempio: Indossa dei guanti quando fa molto freddo.'],
['Hai mal di collo dopo aver dormito in una posizione scomoda.','Cosa puoi fare?','Muovere il collo con calma e osservare come evolve il fastidio.','Per esempio: Evita movimenti bruschi se il collo è dolorante.'],
['Hai un corpo estraneo nell’occhio e non riesci a eliminarlo facilmente.','Cosa fai?','Eviti di strofinare l’occhio e chiedi assistenza se il problema continua.','Per esempio: Se il fastidio persiste, chiedi consiglio a un professionista.'],
['Hai dolore a un ginocchio dopo un movimento improvviso.','Cosa fai?','Smetti di forzarlo e valuti il problema se il dolore persiste.','Per esempio: Evita di continuare l’attività se il dolore aumenta.'],
['Hai le labbra molto secche in inverno.','Cosa puoi fare?','Usare un prodotto adatto per idratarle.','Per esempio: Puoi usare un balsamo per le labbra.'],
['Hai difficoltà a muovere una parte del corpo dopo un trauma.','Cosa fai?','Chiedi una valutazione professionale.','Per esempio: Dopo un trauma importante è meglio non improvvisare.'],
['Ti accorgi che hai difficoltà a respirare.','Cosa fai?','Cerchi immediatamente assistenza, soprattutto se la difficoltà è importante.','Per esempio: In una situazione urgente contatta i servizi di emergenza.']
];
function buildSituations(){return repeat100(situationsBase.map(x=>({kind:'mc',prompt:`${x[0]} ${x[1]}`,correct:x[2],options:opts(x[2],situationsBase.map(y=>y[2])),feedback:fb('Questa è la scelta più coerente con la situazione descritta.',x[3])})))}

const verbsBase=[
['avere','Io ___ mal di testa.','ho',['ha','hai','hanno']],['sentire','Lei ___ dolore alla spalla.','sente',['sento','sentono','sentire']],['muovere','Tu ___ il braccio lentamente.','muovi',['muove','muovete','muovere']],['piegare','Io ___ il ginocchio con difficoltà.','piego',['piega','piegano','piegare']],['alzare','Noi ___ le mani.','alziamo',['alza','alzate','alzare']],['abbassare','Voi ___ la testa.','abbassate',['abbassa','abbassano','abbassare']],['aprire','Lui ___ la bocca.','apre',['apri','aprono','aprire']],['chiudere','Lei ___ gli occhi.','chiude',['chiudi','chiudono','chiudere']],['lavare','Io ___ le mani prima di mangiare.','lavo',['lava','lavano','lavare']],['toccare','Non ___ la ferita.','toccare',['tocchi','toccate','toccando']],['respirare','Dopo la corsa noi ___.','respiriamo',['respira','respirate','respirare']],['camminare','Lui ___ lentamente per il dolore al piede.','cammina',['camminano','cammini','camminare']],['masticare','Noi ___ il cibo lentamente.','mastichiamo',['mastica','masticate','masticare']],['deglutire','Lei ___ con difficoltà.','deglutisce',['deglutiscono','deglutiamo','deglutire']],['guardare','Tu ___ lo schermo da molto tempo.','guardi',['guarda','guardate','guardare']],['ascoltare','Io ___ con attenzione.','ascolto',['ascolta','ascoltano','ascoltare']],['usare','Voi ___ le mani per scrivere.','usate',['usa','usano','usare']],['piegarsi','Io ___ in avanti per prendere la borsa.','mi piego',['si piega','vi piegate','piegarsi']],['sedersi','Noi ___ sulla sedia.','ci sediamo',['si siede','vi sedete','sedersi']],['riposare','Dopo la camminata loro ___.','riposano',['riposa','riposiamo','riposare']]
];
function buildVerbs(){return repeat100(verbsBase.map(v=>({kind:'mc',prompt:v[1],correct:v[2],options:opts(v[2],v[3]),feedback:fb(`La forma corretta è “${v[2]}”.`,`Per esempio: ${v[0].charAt(0).toUpperCase()+v[0].slice(1)} è un verbo utile per parlare del corpo e dei movimenti.`)})))}

function buildFlash(){return repeat100(terms.map(([w,u,e,d])=>({kind:'flash',word:w,ua:u,definition:d,example:e})))}
function buildMixed(){const all=[...buildGuess(),...buildComplete(),...buildIntruso(),...buildRoleplay(),...buildSituations(),...buildVerbs()];return shuffle(all).slice(0,N)}
const builders={mixed:buildMixed,guess:buildGuess,intruso:buildIntruso,complete:buildComplete,roleplay:buildRoleplay,situations:buildSituations,verbs:buildVerbs,flashcard:buildFlash};
const info={mixed:['🎯 Quiz misto','Lessico del corpo e significati nel contesto.'],guess:['💡 Indovina la parola','Leggi la descrizione e trova la parte del corpo.'],intruso:['🕵️ Trova l’intruso','Quale parola non appartiene al gruppo?'],complete:['✏️ Completa la frase','Scegli la parola che completa la situazione.'],roleplay:['🗣️ Giochi di ruolo','Situazioni reali per parlare del corpo e dei movimenti.'],situations:['💡 Situazioni da risolvere','Leggi la situazione e scegli cosa fare o dire.'],verbs:['⚙️ Verbi del corpo','Scegli la forma verbale corretta nel contesto.'],flashcard:['🗂️ Flashcard','Italiano → ucraino → spiegazione ed esempio.']};
let type=new URLSearchParams(location.search).get('type')||'mixed';if(!builders[type])type='mixed';let questions=builders[type](),index=0,score=0,answered=false;
const $=id=>document.getElementById(id);const renderHeader=()=>{$('eyebrow').textContent=info[type][0];$('title').textContent=info[type][0].replace(/^\S+\s/,'');$('subtitle').textContent=info[type][1]};

const SIMPLE_PROMPT_REPLACEMENTS=[["presentare un sintomo", "avere un sintomo"], ["assumere un farmaco", "prendere un farmaco"], ["recarsi dal medico", "andare dal medico"], ["somministrazione", "servizio"], ["comunicazione", "modo di parlare"], ["somministrare", "dare"], ["disponibilità", "posti liberi"], ["preparazione", "preparazione"], ["consumazione", "ordine"], ["prescrizione", "ricetta"], ["comprensione", "capire"], ["prenotazione", "prenotazione"], ["attraversare", "passare"], ["raggiungere", "arrivare"], ["soggiornare", "stare"], ["necessitare", "avere bisogno di"], ["specificare", "dire"], ["selezionare", "scegliere"], ["selezionate", "scegli"], ["circostanza", "situazione"], ["manifestare", "avere"], ["prescrivere", "dare"], ["consigliare", "dire di"], ["comprendere", "capire"], ["espressione", "frase"], ["disponibile", "libero"], ["insaporire", "dare sapore"], ["acquistare", "comprare"], ["effettuare", "fare"], ["utilizzare", "usare"], ["richiedere", "chiedere"], ["consentire", "permettere"], ["proseguire", "continuare"], ["alloggiare", "stare"], ["pernottare", "dormire"], ["conservare", "tenere"], ["verificare", "controllare"], ["comunicare", "dire"], ["situazione", "caso"], ["consultare", "chiedere a"], ["preferenza", "scelta"], ["prossimità", "vicinanza"], ["consumare", "mangiare"], ["recarsi a", "andare a"], ["richiesta", "domanda"], ["necessita", "ha bisogno di"], ["seleziona", "scegli"], ["procedere", "andare"], ["malessere", "problema"], ["esprimere", "dire"], ["preferire", "volere di più"], ["adiacente", "vicino"], ["macinare", "fare la farina"], ["macinato", "tritato"], ["frumento", "grano"], ["sostanza", "prodotto"], ["sostanze", "prodotti"], ["assumere", "prendere"], ["utilizzo", "uso"], ["indicare", "dire"], ["reperire", "trovare"], ["verifica", "controlla"], ["pietanza", "piatto"], ["pietanze", "piatti"], ["disturbo", "problema"], ["richiede", "chiede"], ["incrocio", "incrocio"], ["consumo", "mangiare"], ["recarsi", "andare"], ["bevanda", "bibita"], ["sintomo", "problema"], ["ubicato", "che si trova"], ["situato", "che si trova"], ["indica", "vuol dire"]];
function simplifyPrompt(text){let s=String(text||'');for(const [from,to] of SIMPLE_PROMPT_REPLACEMENTS){s=s.replace(new RegExp(from.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),to)}return s}
function render(){answered=false;$('feedback').className='feedback';$('feedback').innerHTML='';$('progressText').textContent=`${index+1} / ${S}`;$('fill').style.width=`${((index+1)/S)*100}%`;const q=questions[index];$('typeLabel').textContent=info[type][0];$('prev').disabled=index===0;$('next').textContent=index===S-1?'Termina':'Avanti →';if(q.kind==='flash'){renderFlash(q);return}if(q.kind==='intruso'){renderIntruso(q);return}renderMC(q)}
function renderMC(q){$('content').innerHTML=`<div class="question">${simplifyPrompt(q.prompt)}</div><div class="answers">${q.options.map((o,i)=>`<button class="answer" data-i="${i}">${o}</button>`).join('')}</div>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answerMC(q,b));}
function renderIntruso(q){$('content').innerHTML=`<div class="question">${simplifyPrompt(q.prompt)}</div><div class="answers">${shuffle(q.choices).map(o=>`<button class="answer">${o}</button>`).join('')}</div>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answerIntruso(q,b));}
function answerMC(q,b){if(answered)return;answered=true;const ok=b.textContent===q.correct;if(ok)score++;document.querySelectorAll('.answer').forEach(x=>{x.disabled=true;if(x.textContent===q.correct)x.classList.add('correct')});if(!ok)b.classList.add('wrong');showFeedback(ok,q.feedback)}
function answerIntruso(q,b){if(answered)return;answered=true;const ok=b.textContent===q.correct;if(ok)score++;document.querySelectorAll('.answer').forEach(x=>{x.disabled=true;if(x.textContent===q.correct)x.classList.add('correct')});if(!ok)b.classList.add('wrong');showFeedback(ok,q.feedback)}
function showFeedback(ok,f){$('feedback').className=`feedback show ${ok?'good':'bad'}`;$('feedback').innerHTML=`<strong>${ok?'✓ Corretto':'✕ Non è la risposta corretta'}</strong><div>${f.why}</div><div class="example">Esempio reale: <em>${f.example}</em></div>`}
function renderFlash(q){$('content').innerHTML=`<div class="flashcard" tabindex="0" id="flashcard"><div class="flash-inner"><div class="flash-face flash-front"><div>${q.word}</div><small>Clicca per girare</small></div><div class="flash-face flash-back"><div class="uk">${q.ua}</div><div class="definition">${q.definition}</div><div class="example">${q.example}</div><small>Clicca per tornare indietro</small></div></div></div><div class="flash-hint">Tocca la carta per vedere la traduzione e l’esempio.</div>`;const c=$('flashcard');c.onclick=()=>c.classList.toggle('flipped');c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();c.classList.toggle('flipped')}}}
$('prev').onclick=()=>{if(index>0){index--;render()}};$('next').onclick=()=>{if(index<S-1){index++;render()}else{finish()}};
function finish(){$('card').style.display='none';$('end').classList.add('show');$('score').textContent=`Hai risposto correttamente a ${score} domande su ${S}.`}
renderHeader();render();
