const I = [
{p:'alto/a',u:'високий / висока',m:'Di statura maggiore rispetto alla media.',e:'Marco è alto e gioca a pallavolo.',c:['È di statura molto maggiore rispetto ai suoi amici.','Quando entra nella stanza si nota subito perché è molto grande in altezza.']},
{p:'basso/a',u:'низький / низька',m:'Di statura minore rispetto alla media.',e:'Mia sorella è bassa, ma è molto sportiva.',c:['È di statura più piccola rispetto alle altre persone.','Anche se è basso, raggiunge facilmente il canestro.']},
{p:'magro/a',u:'худий / худа',m:'Ha un corpo con poca massa o grasso.',e:'Luca è magro perché corre ogni giorno.',c:['Ha un fisico molto esile e poco pesante.','Dopo molti mesi di sport è diventata più magra.']},
{p:'robusto/a',u:'міцний / міцна; кремезний / кремезна',m:'Ha un corpo forte e di struttura grande.',e:'Paolo è robusto e molto forte.',c:['Ha una corporatura grande e forte.','Il ragazzo ha un fisico robusto e porta facilmente gli scatoloni.']},
{p:'capelli lunghi',u:'довге волосся',m:'Capelli che arrivano oltre le spalle o comunque hanno molta lunghezza.',e:'Anna ha i capelli lunghi e mossi.',c:['I suoi capelli arrivano quasi alla vita.','Non vuole tagliarsi i capelli perché li porta molto lunghi.']},
{p:'capelli corti',u:'коротке волосся',m:'Capelli tagliati con poca lunghezza.',e:'Mio fratello ha i capelli corti.',c:['Porta un taglio con pochissimi capelli ai lati.','Dopo l’estate ha deciso di tagliare i capelli molto corti.']},
{p:'capelli ricci',u:'кучеряве волосся',m:'Capelli con una forma a riccioli o onde strette.',e:'Giulia ha i capelli ricci e voluminosi.',c:['I suoi capelli formano tanti piccoli riccioli.','Quando piove i suoi capelli diventano ancora più ricci.']},
{p:'capelli lisci',u:'пряме волосся',m:'Capelli senza riccioli, che cadono dritti.',e:'Sara ha i capelli lisci e lunghi.',c:['I capelli cadono dritti sulle spalle.','Non ha bisogno della piastra perché ha già i capelli lisci.']},
{p:'occhi azzurri',u:'блакитні очі',m:'Occhi di colore azzurro.',e:'Ha gli occhi azzurri come il cielo.',c:['Il colore dei suoi occhi è simile a quello del cielo.','Quando sorride si notano subito i suoi occhi azzurri.']},
{p:'occhi marroni',u:'карі очі',m:'Occhi di colore marrone.',e:'Mio padre ha gli occhi marroni.',c:['Ha gli occhi di un colore scuro e caldo.','I suoi occhi marroni sono molto espressivi.']},
{p:'barba',u:'борода',m:'Peli che crescono sul viso, soprattutto mento e guance.',e:'Da qualche mese porta la barba.',c:['Ha deciso di non radersi e ora ha molti peli sul viso.','La barba gli sta molto bene.']},
{p:'occhiali',u:'окуляри',m:'Lenti montate su una struttura che si porta davanti agli occhi.',e:'Porta gli occhiali quando legge.',c:['Li mette soprattutto per vedere meglio da lontano.','Senza gli occhiali non riesce a leggere bene.']},
{p:'elegante',u:'елегантний / елегантна',m:'Ha un aspetto curato e raffinato, soprattutto nel modo di vestirsi.',e:'Alla festa era molto elegante.',c:['Indossa un completo curato e raffinato.','Per la cerimonia si è vestita in modo molto elegante.']},
{p:'casual',u:'повсякденний / невимушений',m:'Semplice e informale, adatto alla vita quotidiana.',e:'A scuola preferisco uno stile casual.',c:['Indossa jeans, sneakers e una maglietta: ha uno stile informale.','Per il weekend sceglie sempre un abbigliamento semplice e casual.']},
{p:'sorridente',u:'усміхнений / усміхнена',m:'Che sorride spesso o ha un’espressione felice.',e:'È sempre sorridente e mette tutti di buon umore.',c:['Quando incontra gli amici ha sempre un grande sorriso.','È una persona molto sorridente e positiva.']},
{p:'serio/a',u:'серйозний / серйозна',m:'Ha un comportamento concentrato e poco scherzoso.',e:'Il nuovo insegnante è molto serio.',c:['Durante il lavoro non scherza quasi mai e rimane concentrato.','Ha un’espressione seria e parla poco.']},
{p:'giovane',u:'молодий / молода',m:'Che ha pochi anni o un’età relativamente bassa.',e:'È una giovane collega molto preparata.',c:['Ha venticinque anni, quindi è ancora molto giovane.','Il gruppo è formato soprattutto da persone giovani.']},
{p:'anziano/a',u:'літній / літня; похилого віку',m:'Che ha molti anni, soprattutto in età avanzata.',e:'Una signora anziana mi ha indicato la strada.',c:['È una persona di età avanzata.','Il quartiere è frequentato da molte persone anziane.']},
{p:'gentile',u:'добрий / ввічливий',m:'Tratta gli altri con cortesia e attenzione.',e:'La commessa è stata molto gentile con me.',c:['Ti ascolta, ti aiuta e ti parla con educazione.','È sempre gentile con i clienti.']},
{p:'simpatico/a',u:'приємний / приємна; симпатичний / симпатична',m:'Piacevole e capace di mettere gli altri a proprio agio.',e:'Il nuovo collega è davvero simpatico.',c:['Parla con tutti, scherza e fa sentire le persone a loro agio.','È una persona piacevole con cui è facile parlare.']},
{p:'antipatico/a',u:'неприємний / неприємна',m:'Che non piace o che tratta gli altri in modo sgradevole.',e:'Quel ragazzo mi sembra antipatico.',c:['Parla male con tutti e non è piacevole stare con lui.','All’inizio mi è sembrata un po’ antipatica.']},
{p:'socievole',u:'товариський / товариська',m:'Ama stare con le persone e fare nuove conoscenze.',e:'Marta è molto socievole e conosce tutti.',c:['Parla facilmente con persone che non conosce.','È socievole: alle feste fa subito nuove amicizie.']},
{p:'timido/a',u:'сором’язливий / сором’язлива',m:'Fa fatica a parlare o a stare al centro dell’attenzione.',e:'Da bambino ero molto timido.',c:['Quando incontra persone nuove parla poco e arrossisce.','È troppo timida per parlare davanti a tutti.']},
{p:'estroverso/a',u:'екстравертний / екстравертна',m:'Aperto, comunicativo e a proprio agio con gli altri.',e:'Mio fratello è estroverso e ama le feste.',c:['Parla facilmente con tutti e ama stare in gruppo.','È molto estroversa e non ha problemi a conoscere persone nuove.']},
{p:'introverso/a',u:'інтровертний / інтровертна',m:'Preferisce ambienti tranquilli e pochi rapporti molto stretti.',e:'È introverso e ama passare il tempo da solo.',c:['Preferisce stare con poche persone e avere momenti di tranquillità.','Non ama le feste affollate perché è piuttosto introversa.']},
{p:'tranquillo/a',u:'спокійний / спокійна',m:'Calmo e poco agitato.',e:'È una persona tranquilla e paziente.',c:['Anche nei momenti difficili mantiene la calma.','È molto tranquillo: non si arrabbia quasi mai.']},
{p:'nervoso/a',u:'нервовий / нервова',m:'Agitato, preoccupato o facilmente irritabile.',e:'Prima dell’esame ero molto nervosa.',c:['Continua a muovere le mani perché è agitato.','È nervoso perché deve parlare davanti a molte persone.']},
{p:'paziente',u:'терплячий / терпляча',m:'Sa aspettare senza arrabbiarsi e affronta le difficoltà con calma.',e:'La maestra è paziente con i bambini.',c:['Spiega la stessa cosa molte volte senza arrabbiarsi.','È paziente e aspetta con calma il suo turno.']},
{p:'impaziente',u:'нетерплячий / нетерпляча',m:'Fa fatica ad aspettare e vuole che le cose accadano subito.',e:'Sono impaziente: voglio sapere subito il risultato.',c:['Controlla continuamente l’orologio perché non sa aspettare.','È impaziente e vuole tutto immediatamente.']},
{p:'generoso/a',u:'щедрий / щедра',m:'È disposto a dare tempo, aiuto o cose agli altri.',e:'È molto generoso con i suoi amici.',c:['Offre spesso il suo aiuto e condivide volentieri ciò che ha.','È generosa: pensa spesso agli altri.']},
{p:'avaro/a',u:'скупий / скупа',m:'Non ama spendere o condividere il proprio denaro.',e:'È così avaro che non offre mai un caffè.',c:['Non vuole spendere soldi nemmeno per piccole cose.','È molto avaro e controlla ogni centesimo.']},
{p:'disponibile',u:'готовий допомогти; доступний',m:'Pronto ad aiutare o a dedicare tempo agli altri.',e:'Se hai bisogno, sono sempre disponibile.',c:['Se qualcuno ha un problema, cerca subito di aiutare.','È sempre disponibile quando un collega ha bisogno.']},
{p:'egoista',u:'егоїстичний / егоїстична',m:'Pensa soprattutto ai propri interessi e poco a quelli degli altri.',e:'È egoista e pensa solo a se stesso.',c:['Prende sempre la decisione migliore per sé senza pensare agli altri.','Non vuole condividere nulla: è molto egoista.']},
{p:'onesto/a',u:'чесний / чесна',m:'Dice la verità e non inganna gli altri.',e:'È una persona onesta: dice sempre quello che pensa.',c:['Restituisce un portafoglio trovato per strada senza prendere nulla.','È onesto e ammette quando ha sbagliato.']},
{p:'sincero/a',u:'щирий / щира',m:'Esprime ciò che pensa o prova senza fingere.',e:'È sincera e mi dice sempre la verità.',c:['Ti dice davvero quello che pensa, anche quando non è facile.','Preferisco una persona sincera a qualcuno che finge.']},
{p:'bugiardo/a',u:'брехливий / брехлива',m:'Dice cose non vere per ingannare gli altri.',e:'Non fidarti di lui: è un bugiardo.',c:['Racconta spesso cose false per evitare problemi.','È bugiarda e cambia versione ogni volta.']},
{p:'educato/a',u:'вихований / ввічливий',m:'Rispetta le regole di buona educazione.',e:'Il bambino è molto educato.',c:['Saluta, ringrazia e chiede le cose con gentilezza.','È educata: dice sempre “per favore” e “grazie”.']},
{p:'maleducato/a',u:'невихований / неввічливий',m:'Non rispetta le regole di buona educazione.',e:'È stato maleducato con il cameriere.',c:['Non saluta, interrompe gli altri e parla in modo sgarbato.','Il suo comportamento è stato davvero maleducato.']},
{p:'preciso/a',u:'точний / точна; акуратний',m:'Fa le cose con attenzione e senza errori.',e:'Anna è precisa e controlla tutto due volte.',c:['Controlla ogni dettaglio prima di consegnare il lavoro.','È molto preciso e non lascia quasi mai errori.']},
{p:'disordinato/a',u:'неохайний / неохайна; безладний',m:'Non mantiene ordine nelle cose o negli spazi.',e:'Mio fratello è disordinato: lascia tutto sul tavolo.',c:['La sua stanza è piena di vestiti e oggetti dappertutto.','È disordinata e perde spesso le sue cose.']},
{p:'puntuale',u:'пунктуальний / пунктуальна',m:'Arriva all’ora stabilita.',e:'Giulia è sempre puntuale agli appuntamenti.',c:['Arriva sempre all’orario concordato.','È puntuale: non fa mai aspettare gli altri.']},
{p:'ritardatario/a',u:'той, хто запізнюється',m:'Arriva spesso dopo l’orario stabilito.',e:'Luca è un ritardatario: arriva sempre tardi.',c:['Ha appuntamento alle nove ma arriva quasi sempre alle nove e venti.','È un ritardatario e fa aspettare tutti.']},
{p:'affidabile',u:'надійний / надійна',m:'Su cui si può contare e che mantiene le promesse.',e:'È una collega affidabile.',c:['Quando promette qualcosa, puoi essere sicuro che lo farà.','Mi fido di lui perché è molto affidabile.']},
{p:'irresponsabile',u:'безвідповідальний / безвідповідальна',m:'Non presta abbastanza attenzione ai propri doveri e alle conseguenze.',e:'È irresponsabile: non rispetta mai gli impegni.',c:['Non fa ciò che deve fare e non pensa alle conseguenze.','Lascia sempre i suoi compiti agli altri: è irresponsabile.']},
{p:'coraggioso/a',u:'сміливий / смілива',m:'Affronta situazioni difficili o pericolose senza grande paura.',e:'È stato coraggioso e ha aiutato il bambino.',c:['Non ha paura di affrontare una situazione difficile.','È molto coraggiosa: prova sempre a superare le sue paure.']},
{p:'prudente',u:'обережний / обережна',m:'Agisce con attenzione per evitare rischi o problemi.',e:'È prudente quando guida.',c:['Prima di agire pensa ai possibili rischi.','È prudente e non prende decisioni senza riflettere.']},
{p:'curioso/a',u:'допитливий / допитлива',m:'Vuole sapere, scoprire e capire cose nuove.',e:'Sono curioso e faccio molte domande.',c:['Fa tante domande perché vuole capire tutto.','È molto curiosa e ama imparare cose nuove.']},
{p:'distratto/a',u:'неуважний / неуважна',m:'Presta poca attenzione e può dimenticare facilmente le cose.',e:'Sono distratto e ho dimenticato le chiavi.',c:['Pensa ad altro e spesso dimentica dove mette le cose.','È distratta: ha lasciato di nuovo il telefono a casa.']},
{p:'creativo/a',u:'творчий / творча',m:'Ha idee originali e trova soluzioni nuove.',e:'Marta è creativa e inventa sempre nuove attività.',c:['Trova idee originali che agli altri non vengono in mente.','È creativo e ama inventare nuovi progetti.']},
{p:'pigro/a',u:'лінивий / лінива',m:'Non ha voglia di fare attività o lavorare.',e:'Nel weekend sono un po’ pigro.',c:['Preferisce stare sul divano invece di fare le faccende.','È pigra e rimanda spesso quello che deve fare.']},
{p:'lavoratore/lavoratrice',u:'працьовитий / працьовита',m:'Lavora molto e si impegna con costanza.',e:'Mia madre è una lavoratrice instancabile.',c:['Si impegna molto e non si ferma facilmente davanti alle difficoltà.','È una persona molto lavoratrice e responsabile.']},
{p:'ambizioso/a',u:'амбіційний / амбітна',m:'Ha obiettivi importanti e vuole ottenere risultati elevati.',e:'È ambiziosa e vuole crescere professionalmente.',c:['Vuole raggiungere obiettivi importanti nella sua carriera.','È molto ambizioso: vuole sempre migliorare.']},
{p:'modesto/a',u:'скромний / скромна',m:'Non cerca di mostrarsi migliore degli altri.',e:'Nonostante il successo, rimane modesta.',c:['Ha molti risultati ma non ama vantarsi.','È modesto e non parla mai dei suoi successi.']},
{p:'arrogante',u:'зарозумілий / зарозуміла',m:'Si considera superiore agli altri e lo mostra nel comportamento.',e:'Il nuovo collega è un po’ arrogante.',c:['Parla agli altri come se fosse migliore di loro.','È arrogante e non ascolta le opinioni degli altri.']},
{p:'sensibile',u:'чутливий / чутлива',m:'Reagisce intensamente alle emozioni e ai sentimenti.',e:'È molto sensibile e si emoziona facilmente.',c:['Si emoziona facilmente davanti a una storia triste.','È sensibile e nota subito quando qualcuno sta male.']},
{p:'testardo/a',u:'впертий / вперта',m:'Fa fatica a cambiare idea anche quando sarebbe utile.',e:'Mio padre è testardo e non cambia mai idea.',c:['Continua a fare come vuole anche quando gli altri gli danno buoni consigli.','È testarda: non vuole mai ammettere di aver sbagliato.']},
{p:'permaloso/a',u:'образливий / образлива',m:'Si offende facilmente per parole o critiche.',e:'È un po’ permaloso: prende tutto sul personale.',c:['Si offende anche per una piccola battuta.','È permalosa e non accetta bene le critiche.']},
{p:'allegro/a',u:'веселий / весела',m:'Di buon umore e pieno di energia positiva.',e:'È una persona allegra e fa ridere tutti.',c:['Sorride spesso e porta energia positiva nel gruppo.','È allegra anche quando la giornata è difficile.']},
{p:'triste',u:'сумний / сумна',m:'Prova dispiacere o poca felicità.',e:'Oggi è triste perché ha ricevuto una brutta notizia.',c:['Ha poca voglia di parlare e sembra molto giù di morale.','È triste dopo aver litigato con un amico.']},
{p:'ottimista',u:'оптимістичний / оптимістична',m:'Tende a vedere il lato positivo delle situazioni.',e:'Sono ottimista: penso che andrà tutto bene.',c:['Anche davanti a un problema pensa che ci sia una soluzione.','È ottimista e cerca sempre qualcosa di positivo.']},
{p:'pessimista',u:'песимістичний / песимістична',m:'Tende ad aspettarsi risultati negativi.',e:'È pessimista e pensa sempre al peggio.',c:['Prima di iniziare pensa subito che qualcosa andrà male.','È pessimista: vede soprattutto i problemi.']},
{p:'determinato/a',u:'рішучий / рішуча',m:'Deciso a raggiungere un obiettivo e non arrendersi facilmente.',e:'È determinata e non si arrende mai.',c:['Ha un obiettivo e continua a lavorare anche quando è difficile.','È molto determinato: vuole arrivare fino alla fine.']},
{p:'insicuro/a',u:'невпевнений / невпевнена',m:'Ha poca fiducia nelle proprie capacità o decisioni.',e:'È insicura e ha paura di sbagliare.',c:['Dubita spesso delle proprie capacità e chiede continuamente conferme.','È insicuro e non sa quale decisione prendere.']}
];

const N=100,S=15;
let state={type:'mixed',pool:[],i:0,score:0,locked:false};
const $=id=>document.getElementById(id);
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function others(item,key,count=3){return shuffle(I.filter(x=>x!==item).map(x=>x[key])).slice(0,count)}
function unique(items){const seen=new Set();return items.filter(x=>{const k=x.id;if(seen.has(k))return false;seen.add(k);return true})}
function makeId(kind,item,variant){return `${kind}|${item.p}|${variant}`}
function poolMeaning(){const out=[];I.forEach(x=>{['Qual è il significato di','Che cosa vuol dire'].forEach((label,v)=>out.push({id:makeId('meaning',x,v),kind:'meaning',q:`${label} “${x.p}”?`,a:x.m,opts:shuffle([x.m,...others(x,'m')]),ex:x.e,uk:x.u}))});return shuffle(out).slice(0,N)}
function poolTrueFalse(){const out=[];I.forEach(x=>{for(let v=0;v<2;v++){const wrong=I.filter(y=>y!==x)[Math.floor(Math.random()*(I.length-1))];const ok=(v===0);out.push({id:makeId('truefalse',x,v),kind:'truefalse',q:`“${x.p}” — ${ok?x.m:wrong.m}`,a:ok?'Vero':'Falso',opts:['Vero','Falso'],ex:x.e,uk:x.u})}});return shuffle(out).slice(0,N)}
function poolContext(){const out=[];I.forEach(x=>x.c.forEach((c,v)=>out.push({id:makeId('context',x,v),kind:'context',q:c,a:x.p,opts:shuffle([x.p,...others(x,'p')]),ex:x.e,uk:x.u})));return shuffle(out).slice(0,N)}
function poolComplete(){const out=[];I.forEach(x=>{const sentence=x.e.replace(new RegExp(x.p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'_____');for(let v=0;v<2;v++)out.push({id:makeId('complete',x,v),kind:'complete',q:sentence,a:x.p,opts:shuffle([x.p,...others(x,'p')]),ex:x.e,uk:x.u})});return shuffle(out).slice(0,N)}
function poolPhrase(){const out=[];I.forEach(x=>{for(let v=0;v<2;v++)out.push({id:makeId('phrase',x,v),kind:'phrase',q:`${v?'Quale parola descrive meglio questa persona?':'Scegli la parola più adatta:'} ${x.m}`,a:x.p,opts:shuffle([x.p,...others(x,'p')]),ex:x.e,uk:x.u})});return shuffle(out).slice(0,N)}
function poolFlash(){return shuffle(I).slice(0,S).map((x,i)=>({id:`flash|${x.p}|${i}`,flash:true,kind:'flash',q:x.p,a:x.u,meaning:x.m,ex:x.e,uk:x.u}))}
function poolMixed(){const all=[...poolMeaning(),...poolTrueFalse(),...poolContext(),...poolComplete(),...poolPhrase()];return shuffle(all).slice(0,N)}
function getPool(type){if(type==='flash')return poolFlash();if(type==='truefalse')return poolTrueFalse();if(type==='meaning')return poolMeaning();if(type==='context')return poolContext();if(type==='complete')return poolComplete();if(type==='phrase')return poolPhrase();return poolMixed()}
const labels={flash:'Flashcard',truefalse:'Vero o falso?',meaning:'Che cosa significa?',context:'Descrivi la persona',complete:'Completa la descrizione',phrase:'Trova la parola',mixed:'Quiz misto'};
function start(){state.type=new URLSearchParams(location.search).get('type')||'mixed';state.pool=getPool(state.type);state.i=0;state.score=0;show()}
function show(){state.locked=false;const x=state.pool[state.i];$('eyebrow').textContent='👤 Personalità e persone';$('title').textContent=labels[state.type];$('subtitle').textContent=state.type==='flash'?'':'Una domanda alla volta.';$('progressText').textContent=`${state.i+1} / ${S}`;$('fill').style.width=((state.i+1)/S*100)+'%';$('feedback').className='feedback';$('feedback').innerHTML='';$('prev').disabled=state.i===0;$('next').disabled=true;
if(x.flash){$('typeLabel').textContent='FLASHCARD';$('content').innerHTML=`<div class="flashcard" tabindex="0" id="flash"><div class="flash-inner"><div class="flash-face flash-front">${esc(x.q)}</div><div class="flash-face flash-back"><div class="uk">${esc(x.a)}</div><div class="definition">${esc(x.meaning)}</div><div class="example">${esc(x.ex)}</div></div></div></div>`;$('flash').onclick=()=>$('flash').classList.toggle('flipped');$('flash').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')$('flash').classList.toggle('flipped')};$('next').disabled=false;return}
$('typeLabel').textContent=labels[state.type].toUpperCase();$('content').innerHTML=`<div class="question">${esc(x.q)}</div><div class="answers">${x.opts.map((o,i)=>`<button class="answer" data-i="${i}">${esc(o)}</button>`).join('')}</div>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)))}
function answer(i){if(state.locked)return;state.locked=true;const x=state.pool[state.i],btns=[...document.querySelectorAll('.answer')],chosen=x.opts[i],ok=chosen===x.a;btns.forEach(b=>b.disabled=true);btns[i].classList.add(ok?'correct':'wrong');const ci=x.opts.indexOf(x.a);if(ci>=0)btns[ci].classList.add('correct');if(ok)state.score++;const fb=$('feedback');fb.className='feedback show '+(ok?'good':'bad');fb.innerHTML=`<strong>${ok?'✓ Corretto':'× Non è la risposta corretta'}</strong><div>${ok?'Esatto.':`La risposta corretta è “${esc(x.a)}”.`}</div><div style="margin-top:6px">Ucraino: <em>${esc(x.uk)}</em></div><div style="margin-top:6px">Esempio: <em>${esc(x.ex)}</em></div>`;$('next').disabled=false}
$('next').onclick=()=>{if(state.i<S-1){state.i++;show()}else end()};$('prev').onclick=()=>{if(state.i>0){state.i--;show()}};
function end(){$('card').style.display='none';$('end').classList.add('show');$('score').textContent=`Hai totalizzato ${state.score} punti su ${S}.`}
start();
